version: "3"

services:
  app:
    image: docker-node-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb+srv://ramzibouzaiene00:123654789ramzi@cluster0.600yn5m.mongodb.net/mern-app-db?retryWrites=true&w=majority
      JWT_SECRET: abc123
    ports:
      - "8080:8080"
    depends_on:
      - mern-app-db
    mern-app-db:
      image: mongo:5.0
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mern-app-db-data:/data/db
volumes: mern-app-db-data
